spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devcamp?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: root
  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql : true